#!/usr/bin/env ruby
#
# Runs Autumn from the command line. This script will not exit until all leaves
# have exited. To use this script as a daemon, see the script/daemon script.

AL_ROOT = File.expand_path("#{File.dirname(__FILE__)}/..")

begin
  require 'autumn'
  require 'autumn/genesis'
rescue LoadError
  require "rubygems"
  require 'autumn'
  require 'autumn/genesis'
end

puts "Loading Autumn #{Autumn::VERSION}"
Autumn::Genesis.new.boot!
