#!/usr/bin/env ruby
#
# Runs Autumn from the command line. This script will not exit until all leaves
# have exited. To use this script as a daemon, see the script/daemon script.

AL_ROOT = File.expand_path("#{File.dirname(__FILE__)}/..")

require 'autumn'
require 'autumn/genesis'

puts "Loading Autumn #{Autumn::Version}"
Autumn::Genesis.new.boot!
